### PR TITLE
changed to vs2010 dependencies, added team project setting, added notifi...

### PR DESCRIPTION
**Pull request by worldspawn**
...cation for build success

This branch changes the solution to a vs2010 solution/project (should still work in 2012). It also added a Tfs_TeamProject config option to filter events by the team project. Finally will also issue notifications for build success's not just failures.

Added team project name to check in message.

It also reference v10 of the tfs assemblies instead of v11.

I left the test project out of the solution... i forgot about it. Files are still there but are still in 2012 format.

### CODE REVIEW

**Comment by timclipsham** [comment]
You accidentally left your HipChat API key, Room ID etc. in the pull request. Probably want to kill that key...

Tried to find your email address to let you know privately but was unable to. Better you find out from me rather than somebody else :D

I've wanted to pull out the config into a separate file since I first built it. It's way too easy to shove it in using the settings designer and forget about it, or manually remove it from the app.config but not have the designer refresh the other files. Any suggestions welcome :)

EDIT:
I found this that might help: https://help.github.com/articles/remove-sensitive-data
I haven't merged your change in yet, so maybe you could use that (or other means ) to remove it from your fork and then resubmit the pull request? (FYI: I've never had to deal with any like this before)

**Comment by worldspawn** [comment]
Gaah! Thanks, I went to some effort to not do that. I missed the ol' settings.settings file. I'll get it out, it's only a notification key thankfully. 

The project "git-tfs" targets different version of the tfs libraries by having a common assembly and separate assemblies for each target version of tfs. Check it out, let me know if that's an approach you think is good.

**Comment by worldspawn** [comment]
As it was the last commit it was easy to fix up
Restage
git reset --soft HEAD^

then make the required changes then
git add --all
git commit -am '...'

then force push
git push -f

**Comment by worldspawn** [comment]
I've restored the test project and added some new tests of the extra notification.

I've also changed the team project scoping feature. The setting is now a string collection that should look per line like this:
TeamProject|12345678

So will allow the service to run in support of multiple team projects, they can each target a different room.

**Comment by timclipsham** [comment]
Thanks for the contribution btw :) I'm surprised somebody else found this project useful - always encouraging.
FYI: I won't be able to merge it until the weekend as I'm busy the next couple of nights.

**RE: Build completion event**
Great, definitely wanted to add this notification! Currently in our HipChat room we get enough notifications as it is (TFS checkins, JIRA, Confluence etc.) so I probably won't use it at this point which is why I hadn't added the event yet. I'll merge it anyway for now; raised #4.

**RE: Team Project | RoomId**
Like it, makes a lot of sense for multiple teams.

Current implementation will likely complicate an IoC implementation, because the INotifier dependency no longer supports a parameterless constructor, so I may refactor that. The HipChatClient module allows the room to be specified when sending a message, so we might be able to change the INotifier public methods to accept the event _and_ the room id to send it to. Then `TfsHipChatEventService` will only need one INotifier (as it does now) rather than many. I think this will simplify the implementation and make it a little more flexible for the future.

> The project "git-tfs" targets different version of the tfs libraries by having a common assembly and separate > assemblies for each target version of tfs. Check it out, let me know if that's an approach you think is good.

I'd actually like to remove that TFS DLL dependency; just something I hadn't got to. I'm only using it for the benefit of having the `CheckinEvent` strongly typed object. Notice that `BuildCompletionEvent` doesn't exist in that TFS assembly (or any others I looked through) and I ended up using a class generated by that visual studio tool from the xml. This would remove the complexity these TFS DLL's add and gives more control over the object model implementation.

> Gaah! Thanks, I went to some effort to not do that. I missed the ol' settings.settings file. I'll get it out, it's only a notification key thankfully.

Good to know, better than an admin one however you might want to regenerate it a second time, see commit 84a5973 (that's got to burn a little haha)
`git add -p` is almost one of _the best_ git features I've ever been shown :)

This has convinced me that storing this data in the App.config just sucks. This problem will be solved: #3

Thanks again, keen to get these changes in!

**Comment by worldspawn** [comment]
Ok I squashed my commits and removed the keys (i think). I'll definitely try out git add -p next time i get a chance. Thanks.

**Comment by timclipsham** [comment]
@worldspawn thanks again for your contribution! I just merged it.

I had a couple of changes I hadn't pushed up that I forgot about, one of which modified the build notification message to hyperlink the ID (a bit like the changeset ID in the check-in message). I merged that change with yours so both the failed and successful message contain the link.

Also I completely removed the need for a TFS DLL dependency as I couldn't compile it with the VS2010 DLL reference (I only have VS2012 installed) and figured it was a good time to get rid of it.

**Pull request merged**
